name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown
          
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        
      - name: Install dependencies
        run: npm ci
        
      - name: Build Chrome extension
        run: npm run build chrome
        
      - name: Build Firefox extension
        run: npm run build firefox
        
      - name: Build Opera extension
        run: npm run build opera
        
      - name: Build Edge extension
        run: npm run build edge
        
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            packages/*.zip
            packages/*.xpi
          body: |
            Release for version ${{ github.ref_name }}
            
            Built extensions for:
            - Chrome
            - Firefox
            - Opera
            - Edge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 